-
  branches:
    only:
    - develop
  version: 1.0.{build}-dev
  configuration: Debug
  install:
    - nuget restore
  image: Visual Studio 2019
  build:
    parallel: true
    verbosity: minimal
  after_build:
    - ps: dotnet publish .\src\MrCMS.Web\MrCMS.Web.csproj -c Debug --no-build
  artifacts:
   - path: '\src\MrCMS.Web\bin\Debug\netcoreapp2.2\publish'
     name: MrCMS.Web
     type: WebDeployPackage
-
  branches:
    only:
    - master
  version: 1.0.{build}-master
  configuration: Release
  image: Visual Studio 2019
  install:
    - nuget restore    
  build:
    parallel: true
    verbosity: minimal
  after_build:
    - ps: dotnet publish .\src\MrCMS.Web\MrCMS.Web.csproj -c Release --no-build
  artifacts:
   - path: '\src\MrCMS.Web\bin\Release\netcoreapp2.2\publish'
     name: MrCMS.Web
     type: WebDeployPackage
-
  branches:
    only:
    - /feature\/.*/
  version: 1.0.{build}-{branch}
  configuration: Debug
  install:
    - ps: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - ps: choco install nodejs-lts --no-progress
#    - ps: choco install dotnet-sdk --version=6.0.101 --no-progress
#    - ps: choco install vcredist140 --no-progress
    - dotnet restore
  image: Visual Studio 2022
  build:
    parallel: true
    verbosity: minimal
  after_build:
    - ps: dotnet publish .\src\MrCMS.Web\MrCMS.Web.csproj -c Debug --no-build
  artifacts:
   - path: '\src\MrCMS.Web\bin\Debug\netcoreapp3.1\publish'
     name: MrCMS.Web
     type: WebDeployPackage
-
  branches:
    only:
    - /release\/.*/
  version: 1.0.{build}-master
  configuration: Release
  image: Visual Studio 2019 Preview
  install:
    - nuget restore    
  build:
    parallel: true
    verbosity: minimal
  after_build:
    - ps: dotnet publish .\src\MrCMS.Web\MrCMS.Web.csproj -c Release --no-build
  artifacts:
   - path: '\src\MrCMS.Web\bin\Release\netcoreapp2.2\publish'
     name: MrCMS.Web
     type: WebDeployPackage